- hosts: localhost
  gather_facts: true
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Install httpd packages
      yum:
        name: httpd
        update_cache: yes
        state: latest

    - name: Enable and start httpd service
      systemd:
        name: httpd
        enabled: yes
        masked: no
        state: started
